### ISSUE TITLE
chatbot

### ISSUE THREAD

**Issue by DivyaThawani14** [webnexus-uk/ChatBot-OpenAI#6]
i am getting this message when i am typing anything in chatbot :"Request failed with status code 401"

**Comment by webnexus-uk** [comment]
The 401 error means Unauthorized.
The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
Have you added your own API Key, if not you can view how to do this from these videos:-

[API Tutorial - Create a Chatbot API with OpenAI in less than 7 minutes](https://youtu.be/Q6PEC4nzldU)

[App Tutorial - Create a Chatbot with OpenAI](https://youtu.be/Q_NyjJLvMAU)

**Comment by webnexus-uk** [comment]
The 401 error means Unauthorized.
The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.
Have you added your own API Key, if not you can view how to do this from these videos:-

[API Tutorial - Create a Chatbot API with OpenAI in less than 7 minutes](https://youtu.be/Q6PEC4nzldU)

[App Tutorial - Create a Chatbot with OpenAI](https://youtu.be/Q_NyjJLvMAU)
